[package]
name = "sn-proto"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
aead = "0.5"
base64 = "0.22"
chacha20poly1305 = { version = "0.10", features = ["std"] }
hkdf = "0.12"
sha2 = "0.10"
postcard = { version = "1", features = ["use-std"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uuid = { version = "1", features = ["serde", "v4"] }
getrandom = "0.2"

[dev-dependencies]
hex = "0.4"
